var metadata = [
    {
        "isActive": true,
        "name": "Rotating Armchair - Black Leather",
        "description": "Armchair with arms matching real world office chair, automatically following the avatar orientation. Metal frame and black leather aspect. (Note: To edit, you must select it by the entity list. Filter on \"seat\" to find it.)",
        "pictureUrl": "https://aleziakurdis.github.io/rotatingArmchairs/pictures/rotating_armchair_blackLeather.jpg",
        "contentUrl": "https://aleziakurdis.github.io/rotatingArmchairs/rotating_armchair_blackLeather.json",
        "type": "ENTITIES_JSON",
        "useServerEntityScript": true,
        "keywords": "chair, furniture, office, meeting",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Rotating Armchair - Very Peri Fabric",
        "description": "Armchair with arms matching real world office chair, automatically following the avatar orientation. Green metallic frame and fabric aspect, color: Very Peri. (Note: To edit, you must select it by the entity list. Filter on \"seat\" to find it.)",
        "pictureUrl": "https://aleziakurdis.github.io/rotatingArmchairs/pictures/rotating_armchair_veryPeri.jpg",
        "contentUrl": "https://aleziakurdis.github.io/rotatingArmchairs/rotating_armchair_veryPeri.json",
        "type": "ENTITIES_JSON",
        "useServerEntityScript": true,
        "keywords": "chair, furniture, office, meeting, fabric",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Rotostool - Red Fabric",
        "description": "Club stool with arms, matching real world office chair, automatically following the avatar orientation. Metal frame and and red fabric aspect. (Note: To edit, you must select it by the entity list. Filter on \"seat\" to find it.)",
        "pictureUrl": "https://aleziakurdis.github.io/rotatingArmchairs/pictures/rotostool_brick.jpg",
        "contentUrl": "https://aleziakurdis.github.io/rotatingArmchairs/rotostool_brick.json",
        "type": "ENTITIES_JSON",
        "useServerEntityScript": true,
        "keywords": "chair, furniture, office, meeting, fabric",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "AK003-1 Metaspaceport",
        "description": "Serverless Overte domain sandbox/home with a dynamic ambience. Broken planet, deep space.",
        "pictureUrl": "https://aleziakurdis.github.io/inertia/AK003/cover.jpg",
        "contentUrl": "https://aleziakurdis.github.io/inertia/AK003/inertia.json",
        "type": "SERVERLESS_JSON",
        "useServerEntityScript": false,
        "keywords": "outer space star planet ",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Ready-Player-Me (Avatar Creation)",
        "description": "Using this Overt application, create and customize an avatar with \"Ready Player Me\", a third party avatar provider. The avatars can be used directly, without have to care about a publicly available storage.",
        "pictureUrl": "https://aleziakurdis.github.io/ready-player-me/icon_inactive.png",
        "contentUrl": "https://aleziakurdis.github.io/ready-player-me/app-ready-player-me.js",
        "type": "APPLICATION",
        "useServerEntityScript": false,
        "keywords": "avatar, creation, customization",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Overte logo (glowing)",
        "description": "Overte 3D glowing logo.",
        "pictureUrl": "https://aleziakurdis.github.io/virkit/overteLogo.jpg",
        "contentUrl": "https://aleziakurdis.github.io/voxecutor/logo_overte_white-color-emissive.fst",
        "type": "MODEL",
        "useServerEntityScript": false,
        "keywords": "logo overte brand",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Tyriam",
        "description": "Ready-Player-Me female avatar.",
        "pictureUrl": "https://aleziakurdis.github.io/virkit/tyriam.jpg",
        "contentUrl": "https://d1a370nemizbjq.cloudfront.net/0d410126-a818-4245-bf7a-78d6628da789.glb",
        "type": "AVATAR",
        "useServerEntityScript": false,
        "keywords": "avatar, female",
        "by": "Alezia Kurdis, Ready-Player-Me",
        "license": "CC BY-NC 4.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Ionized Metal",
        "description": "Material entity that can be used to customize other entities (models or shapes). Ionized metal effect.",
        "pictureUrl": "https://aleziakurdis.github.io/virkit/ionizedMetal.jpg",
        "contentUrl": "https://aleziakurdis.github.io/virkit/ionizedMetal.json",
        "type": "MATERIAL_JSON",
        "useServerEntityScript": false,
        "keywords": "material, iron, steel, hot",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Teleporter Script",
        "description": "Teleporter script. To use, create a shape entity, set the destination url in the \"description\" property, then copy and paste the script url in the \"script\" property that entity. (Make sure to set it collisonless and invisible). ",
        "pictureUrl": "",
        "contentUrl": "https://aleziakurdis.github.io/inertia/AK003/spaceport/teleporter.js",
        "type": "SCRIPT",
        "scriptType": "Client Entity Script",
        "useServerEntityScript": false,
        "keywords": "script teleporter teleportation portal ",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Universtool Club - Navy",
        "description": "Scripted armchairs for Overte virtual worlds. Matching most of the real world office chair. Purple metallic frame and blue navy fabric aspect. (Note: To edit, you must select it by the entity list. Filter on \"seat\" to find it.)",
        "pictureUrl": "https://aleziakurdis.github.io/armchairs/pictures/univestool_club_navy.jpg",
        "contentUrl": "https://aleziakurdis.github.io/armchairs/install_universtool_club_navy.json",
        "type": "ENTITIES_JSON",
        "useServerEntityScript": true,
        "keywords": "armchair, stool, furniture",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Morpheus Armchair - Green leather",
        "description": "Scripted armchairs for Overte virtual worlds. Matching most of the real world office chair. Green leather aspect. (Note: To edit, you must select it by the entity list. Filter on \"seat\" to find it.)",
        "pictureUrl": "https://aleziakurdis.github.io/armchairs/pictures/morpheus_armchair_green_leather.jpg",
        "contentUrl": "https://aleziakurdis.github.io/armchairs/install_morpheus_armchair_green_leather.json",
        "type": "ENTITIES_JSON",
        "useServerEntityScript": true,
        "keywords": "armchair, furniture",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Generic Fire Element",
        "description": "Generic fire element for Fireplace or Campfire. Sound volume can be adjusted in \"userData\" (using a value between 0 and 1). Can be re-scaled larger, the fire effect will follow.",
        "pictureUrl": "https://aleziakurdis.github.io/fire_element/cover.jpg",
        "contentUrl": "https://aleziakurdis.github.io/fire_element/fire_element.json",
        "type": "ENTITIES_JSON",
        "useServerEntityScript": false,
        "keywords": "fire, meeting",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Inertia (AK001)",
        "description": "Serverless Overte domain sandbox/home with a dynamic ambience. (Warning, You might need a strong computer to run this.)",
        "pictureUrl": "https://aleziakurdis.github.io/inertia/AK001/cover.jpg",
        "contentUrl": "https://aleziakurdis.github.io/inertia/AK001/inertia.json",
        "type": "SERVERLESS_JSON",
        "useServerEntityScript": false,
        "keywords": "mathematic, universe",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Hallucense - Purple Radian",
        "description": "Hallucense is a social virtual hallucination emitter. This emits particles effects to the users that are within the range of the smoke cloud generated by the hallucense. The \"Purple Radian\" fragrancy emit in the color range between the blue and the red light.",
        "pictureUrl": "https://aleziakurdis.github.io/hallucense/purpleRadian/cover_purpleRadian.jpg",
        "contentUrl": "https://aleziakurdis.github.io/hallucense/products/purpleRadian.json",
        "type": "ENTITIES_JSON",
        "useServerEntityScript": false,
        "keywords": "ambience, social, club, furniture, ",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    },
    {
        "isActive": true,
        "name": "Hallucense - Classic",
        "description": "Hallucense is a social virtual hallucination emitter. This emits particles effects to the users that are within the range of the smoke cloud generated by the hallucense.",
        "pictureUrl": "https://aleziakurdis.github.io/hallucense/components/cover_Classic.jpg",
        "contentUrl": "https://aleziakurdis.github.io/hallucense/products/hallucense.json",
        "type": "ENTITIES_JSON",
        "useServerEntityScript": false,
        "keywords": "ambience, social, club, furniture",
        "by": "Alezia Kurdis",
        "license": "Apache 2.0",
        "maturityLevel": "everyone"
    }
];
